### ISSUE TITLE
PERC-Incorporate-Perceptions-Repository

### ISSUE THREAD

**Issue by dinodeep** [carnegiemellonracing/driverless#12]
## Task Description:
Install the perceptions library located at [here](https://github.com/carnegiemellonracing/PerceptionsLibrary22a). Create a new perceptions ROS folder that is solely Python

Additionally, create `perceptions/perceptions/utils` folder for the purpose of storing all ROS-related transformation functions and Data node.

## Task Check-list:
- [x] Repository installed on Dale
- [x] Write integration tests (able to import `perc22a`) and run `PerceptionsLibrary22a/scripts/test_setup.py`)
- [x] Create ROS nodes for running Stereo and Lidar pipelines which run and visualize data off of rosbags
- [ ] Add Documentation (to Confluence too)
- [ ] Open Pull Request

## Task Timeline:
- [ ] JIRA (Perceptions Repository Integrated into ROS repo)

Comment any questions and tag reviewers.
