### ISSUE TITLE
TEST-Dummy PR

### ISSUE THREAD

**Issue by dinodeep** [carnegiemellonracing/driverless#14]
## Task Description:
This is a silly empty PR to test if the Github PR checks work for main and are installed such that main branch is valid.

PR will actually consist of making a minor change to the repository and checking if the PR passes the PR check build process

## Task Check-list:
- [ ] make minor change
- [ ] PR passes
- [ ] Open Pull Request

## Task Timeline:
- [ ] Update [Jira](cmr.red/jira) with Task Timeline

Comment any questions and tag reviewers.
