### ISSUE TITLE
PERC-Data File Node

### ISSUE THREAD

**Issue by dinodeep** [carnegiemellonracing/driverless#18]
## Task Description:
Create a node that collects data from rosbags and converts them to `npy` file so that they can be shared with the rest of the perceptions teams for working on it on their local computers without having to ssh into Dale. (modify gitignore to ignore .npy files). Node should be able to take in a parameter that specifies the name of the directory that it will save to.

Additionally, modify ros2_numpy from being a submodule to just having the source inside of the repository so that it doesn't change. This will also prevent people from deleting it and having issues on their computer.

## Task Check-list:
- [x] Create DataFileNode
- [x] Make ros2_numpy source part of driverless
- [x] Add Documentation (to Confluence too)
- [x] Open Pull Request

Comment any questions and tag reviewers.
