### ISSUE TITLE
PLAN-Raceline-Node

### ISSUE THREAD

**Issue by andrewwchong** [carnegiemellonracing/driverless#23]
## Task Description:
Creating a raceline node in python for TUM optimizer
## Task Check-list:
- [ ] Create Initial Node
- [ ] Integrate TUM Optimizer
- [ ] Test functionality
- [ ] Add Documentation (to Confluence too)
- [ ] Open Pull Request

## Task Timeline:
- [ ] Update [Jira](cmr.red/jira) with Task Timeline

@ishinshah @andrewwchong
