### ISSUE TITLE
[SUBTEAM]-[Project name]

### ISSUE THREAD

**Issue by akhandelwal2025** [carnegiemellonracing/driverless#3]
## Task Description:
...

## Task Check-list:
- [ ] ...
- [ ] Write integration tests
- [ ] Add Documentation (to Confluence too)
- [ ] Open Pull Request

## Task Timeline:
- [ ] Update [Smartsheet](https://app.smartsheet.com/sheets/phJjhWq5VvpqHHw8WW5rCRh8Xgccpv8Q96WCMr41?view=grid) with Task Timeline

Comment any questions and tag reviewers.
