### ISSUE TITLE
PERC-Refactor-StereoPredictor

### ISSUE THREAD

**Issue by dinodeep** [carnegiemellonracing/driverless#30]
## Task Description:
`perc22a` underwent a name change due to introducing YOLOv8, so `driverless` must reference the appropriate directory

## Task Check-list:
- [x]  Refactor StereoPredictor node so that it is now the YOLOv5PredictorNode
- [x] Open Pull Request

## Task Timeline:
- [x] Update [Jira](cmr.red/jira) with Task Timeline

Comment any questions and tag reviewers.
