### ISSUE TITLE
PERC-Make-Perceptions Run

### ISSUE THREAD

**Issue by dinodeep** [carnegiemellonracing/driverless#32]
## Task Description:
Make all parts of perceptions successfully run with current `main` branch of pipeline, and ensure that the various parts of the pipeline perform as expected.

## Task Check-list:
- [ ] YOLOPredictor Runs
- [ ] LidarPredictor Runs
- [ ] Write integration tests
- [ ] Add Documentation (to Confluence too)
- [ ] Open Pull Request

## Task Timeline:
- [ ] Update [Jira](cmr.red/jira) with Task Timeline

Comment any questions and tag reviewers.
