### ISSUE TITLE
PLAN-ekf-slam-improvments

### ISSUE THREAD

**Issue by akhandelwal2025** [carnegiemellonracing/driverless#4]
## Task Description:
Improve EKF SLAM Performance

## Task Check-list:
- [ ] Implement Data Association Algorithms
- [ ] Test on Simulator
- [ ] Get everything to work on the 22a Compute
- [ ] Open Pull Request

## Task Timeline:
- [ ] Update [Jira](cmr.red/jira) with Task Timeline

Comment any questions and tag reviewers.
