### ISSUE TITLE
PLAN-ros-testing-node

### ISSUE THREAD

**Issue by aidanlincke** [carnegiemellonracing/driverless#5]
## Task Description:
Create a testing node to verify output from [insert software component]

## Task Check-list:
- [ ] Visualize test component's output
- [ ] Write integration tests
- [ ] Add Documentation (to Confluence too)
- [ ] Open Pull Request

## Task Timeline:
- [ ] Update [Jira](cmr.red/jira) with Task Timeline

Comment any questions and tag reviewers.
